/**
 * Damage-correction context tables extracted from GTDB.
 * Domain: gtdb
 * Valid CDS: 405454325
 * Total AA: 130169615628
 * Auto-generated by extract_damage_context
 */

#pragma once

#include <cstddef>
#include <cstdint>

namespace dart {


// N-terminal AA frequency ratios (position-specific / global)
// Position 1 = first AA after Met
static constexpr float NTERMINAL_FREQ_RATIO[10][20] = {
    {0.935, 0.434, 0.721, 0.720, 0.566, 0.423, 0.705, 0.897, 2.865, 0.541, 0.492, 2.031, 1.091, 0.875, 1.158, 2.155, 1.931, 0.380, 0.300, 0.415},  // pos 1
    {0.685, 0.618, 1.057, 1.057, 0.875, 0.499, 1.049, 1.172, 2.350, 0.789, 0.542, 1.502, 0.795, 1.163, 1.338, 1.119, 1.452, 0.678, 0.682, 0.855},  // pos 2
    {0.677, 0.680, 0.745, 0.807, 1.145, 0.468, 1.044, 1.407, 1.707, 1.081, 0.629, 1.241, 1.150, 1.104, 1.187, 1.206, 1.353, 0.804, 0.766, 0.942},  // pos 3
    {0.689, 0.774, 0.838, 0.863, 1.144, 0.485, 1.010, 1.474, 1.584, 1.141, 0.623, 1.175, 1.053, 1.036, 1.092, 1.146, 1.314, 0.902, 0.756, 0.872},  // pos 4
    {0.717, 0.958, 0.804, 0.788, 1.219, 0.548, 1.024, 1.465, 1.486, 1.199, 0.580, 1.093, 1.046, 1.028, 1.106, 1.117, 1.221, 0.904, 0.853, 0.935},  // pos 5
    {0.781, 0.992, 0.773, 0.765, 1.154, 0.661, 1.018, 1.530, 1.347, 1.179, 0.652, 1.047, 1.076, 0.979, 1.061, 1.089, 1.185, 0.938, 0.847, 0.887},  // pos 6
    {0.887, 1.089, 0.850, 0.788, 1.128, 0.736, 0.959, 1.354, 1.216, 1.218, 0.658, 0.954, 1.092, 0.941, 1.069, 1.074, 1.120, 0.935, 0.876, 0.833},  // pos 7
    {0.965, 1.209, 0.846, 0.803, 1.082, 0.846, 0.923, 1.240, 1.138, 1.235, 0.684, 0.932, 1.051, 0.928, 1.052, 1.066, 1.055, 0.961, 0.897, 0.758},  // pos 8
    {1.002, 1.234, 0.834, 0.811, 1.091, 0.907, 0.898, 1.209, 1.055, 1.228, 0.710, 0.874, 1.020, 0.908, 1.052, 1.062, 1.022, 0.999, 0.914, 0.768},  // pos 9
    {1.040, 1.275, 0.824, 0.817, 1.131, 0.921, 0.875, 1.175, 1.013, 1.250, 0.741, 0.849, 1.017, 0.882, 1.045, 1.032, 0.994, 1.001, 0.901, 0.781}  // pos 10
};

// Distance-binned AA frequency ratios (bin_freq / global_freq)
// Bins: 0-14 (damage zone), 15-29, 30-49, 50-99, 100+ (baseline)
static constexpr float DISTANCE_BINNED_FREQ_RATIO[5][20] = {
    {0.852, 0.975, 0.770, 0.773, 0.991, 0.694, 0.870, 1.154, 1.307, 1.083, 3.072, 0.993, 0.951, 0.887, 1.016, 1.086, 1.108, 0.948, 0.759, 0.738},  // 0-14
    {1.138, 1.367, 0.859, 0.931, 1.036, 0.983, 0.934, 1.006, 0.956, 1.118, 0.814, 0.836, 0.968, 0.985, 0.998, 1.030, 0.957, 1.037, 0.989, 0.848},  // 15-29
    {1.028, 1.152, 0.990, 1.022, 0.989, 1.016, 1.010, 0.989, 0.987, 0.999, 0.817, 0.937, 1.017, 1.005, 0.976, 1.024, 0.996, 1.035, 0.992, 0.943},  // 30-49
    {0.997, 1.089, 1.024, 1.018, 1.013, 1.013, 1.044, 1.012, 0.998, 0.995, 0.877, 0.957, 0.987, 0.995, 1.001, 0.979, 0.974, 1.027, 1.007, 0.998},  // 50-99
    {0.999, 0.945, 1.021, 1.014, 0.996, 1.018, 1.003, 0.988, 0.984, 0.987, 0.916, 1.026, 1.007, 1.009, 1.001, 0.995, 1.001, 0.992, 1.016, 1.033}  // 100+
};

// Codon bigram LLR: log2(P(codon precedes CGG) / P(codon precedes TGG))
// Positive = preceding codon favors original being CGG (Arg)
static constexpr float CODON_BIGRAM_LLR_CGG_TGG[64] = {
-0.458, 0.107, 0.340, -0.120, -0.694, -0.095, 0.556, -0.757,   // AAA-ACT
-0.212, 0.346, 0.293, -0.683, -0.828, 0.224, 0.130, -0.530,   // AGA-ATT
-0.727, 0.234, 0.454, -0.274, -1.010, 0.044, 0.197, -0.663,   // CAA-CCT
-0.852, -0.062, 0.548, -0.689, -1.484, 0.096, 0.047, -0.843,   // CGA-CTT
0.111, 0.673, 0.670, 0.169, -0.484, 0.330, 0.904, -0.474,   // GAA-GCT
-0.745, 0.139, 0.174, -0.524, -1.123, 0.106, 0.253, -0.863,   // GGA-GTT
0.000, -0.029, 0.000, -0.557, -1.052, -0.454, 0.116, -0.916,   // TAA-TCT
-0.701, -0.229, -0.453, -0.669, -1.026, -0.313, -0.301, -0.576  // TGA-TTT
};

// Codon bigram LLR for CGC/CGT vs TGC/TGT (Arg→Cys)
static constexpr float CODON_BIGRAM_LLR_CGX_TGX[64] = {
-0.655, 0.124, 0.305, -0.350, -0.592, 0.311, 0.654, -0.820, 
-0.240, 0.430, 0.125, -0.651, -0.908, 0.466, 0.053, -0.614, 
-0.606, 0.386, 0.509, -0.322, -0.877, 0.400, 0.437, -0.604, 
-0.553, 0.465, 0.720, -0.514, -1.326, 0.243, 0.506, -0.852, 
-0.035, 0.614, 0.530, -0.074, -0.369, 0.757, 0.868, -0.449, 
-0.213, 0.195, 0.297, -0.512, -0.952, 0.300, 0.535, -0.890, 
0.000, 0.127, 0.000, -0.635, -0.997, -0.201, 0.394, -1.037, 
-0.863, 0.092, -0.176, -0.658, -1.204, -0.184, -0.255, -0.620
};

// Forbidden W tripeptide patterns (XWX with LLR < -2)
// If we see these patterns with W at damage position, very likely was R
struct ForbiddenWPattern {
    char aa_before;
    char aa_after;
    float llr;        // log2(observed/expected)
    float r_ratio;    // How much more common XRX is than XWX
};

static constexpr ForbiddenWPattern FORBIDDEN_W_PATTERNS[] = {
    {'M', 'E', -0.65f, 9.2f},
    {'L', 'E', -0.39f, 8.5f},
    {'M', 'K', -0.56f, 8.4f},
    {'I', 'E', -0.55f, 8.0f},
    {'M', 'R', -0.25f, 7.9f},
    {'M', 'Y', -0.73f, 7.9f},
    {'M', 'A', -0.77f, 7.7f},
    {'M', 'H', -0.37f, 7.4f},
    {'M', 'D', -0.56f, 7.4f},
    {'V', 'E', -0.34f, 7.3f},
    {'C', 'E', -0.33f, 7.3f},
    {'E', 'F', -0.02f, 7.1f},
    {'A', 'E', -0.39f, 7.0f},
    {'M', 'T', -0.62f, 6.9f},
    {'M', 'P', -0.74f, 6.9f},
    {'E', 'A', -0.39f, 6.9f},
    {'L', 'D', -0.23f, 6.9f},
    {'L', 'A', -0.43f, 6.8f},
    {'E', 'Y', -0.13f, 6.8f},
    {'M', 'Q', -0.13f, 6.7f},
    {'E', 'I', 0.03f, 6.6f},
    {'K', 'P', -0.92f, 6.6f},
    {'M', 'V', -0.71f, 6.5f},
    {'E', 'P', -0.62f, 6.4f},
    {'M', 'I', -0.49f, 6.4f},
    {'M', 'S', -0.45f, 6.4f},
    {'L', 'R', 0.12f, 6.3f},
    {'E', 'G', -0.39f, 6.3f},
    {'I', 'D', -0.37f, 6.3f},
    {'L', 'Y', -0.56f, 6.3f},
    {'E', 'V', -0.11f, 6.3f},
    {'I', 'R', -0.26f, 6.2f},
    {'E', 'L', 0.22f, 6.2f},
    {'I', 'K', -0.25f, 6.2f},
    {'K', 'A', -0.81f, 6.1f},
    {'R', 'A', -0.01f, 6.0f},
    {'L', 'K', -0.30f, 6.0f},
    {'E', 'E', -0.19f, 6.0f},
    {'Q', 'E', -0.30f, 6.0f},
    {'R', 'E', -0.18f, 6.0f},
    {'A', 'A', -0.06f, 6.0f},
    {'Y', 'E', -0.13f, 6.0f},
    {'V', 'D', -0.11f, 6.0f},
    {'V', 'A', -0.29f, 5.9f},
    {'K', 'I', -0.01f, 5.9f},
    {'W', 'E', 0.12f, 5.9f},
    {'V', 'R', 0.06f, 5.9f},
    {'Q', 'V', -0.05f, 5.9f},
    {'C', 'K', -0.28f, 5.9f},
    {'M', 'F', -0.36f, 5.9f},
    {'M', 'G', -0.62f, 5.8f},
    {'I', 'A', -0.65f, 5.8f},
    {'V', 'P', -0.37f, 5.8f},
    {'E', 'W', 0.09f, 5.8f},
    {'Q', 'I', 0.09f, 5.8f},
    {'M', 'L', -0.41f, 5.8f},
    {'K', 'R', -0.40f, 5.7f},
    {'Q', 'A', -0.27f, 5.7f},
    {'M', 'N', -0.29f, 5.7f},
    {'M', 'C', -0.50f, 5.7f},
    {'V', 'Y', -0.43f, 5.7f},
    {'E', 'R', 0.07f, 5.7f},
    {'K', 'V', -0.38f, 5.7f},
    {'G', 'P', 0.09f, 5.6f},
    {'D', 'I', 0.16f, 5.6f},
    {'I', 'P', -0.53f, 5.6f},
    {'I', 'Y', -0.44f, 5.6f},
    {'K', 'Y', 0.03f, 5.5f},
    {'L', 'P', -0.21f, 5.5f},
    {'E', 'H', -0.00f, 5.5f},
    {'I', 'T', -0.38f, 5.5f},
    {'R', 'I', 0.14f, 5.4f},
    {'L', 'T', -0.31f, 5.4f},
    {'E', 'M', 0.15f, 5.4f},
    {'R', 'V', 0.09f, 5.4f},
    {'C', 'A', -0.32f, 5.4f},
    {'M', 'M', -0.23f, 5.4f},
    {'K', 'M', -0.14f, 5.4f},
    {'A', 'R', 0.36f, 5.3f},
    {'A', 'D', -0.34f, 5.3f},
    {'L', 'H', 0.15f, 5.3f},
    {'Q', 'Y', 0.15f, 5.3f},
    {'K', 'G', -0.56f, 5.3f},
    {'V', 'V', -0.19f, 5.3f},
    {'V', 'K', -0.36f, 5.3f},
    {'A', 'I', -0.23f, 5.3f},
    {'K', 'E', -0.47f, 5.3f},
    {'L', 'G', -0.31f, 5.3f},
    {'R', 'G', 0.02f, 5.2f},
    {'R', 'Y', 0.19f, 5.2f},
    {'H', 'A', -0.17f, 5.2f},
    {'R', 'D', -0.13f, 5.2f},
    {'K', 'L', 0.02f, 5.2f},
    {'M', 'W', 0.00f, 5.2f},
    {'E', 'D', -0.29f, 5.2f},
    {'Y', 'A', -0.35f, 5.2f},
    {'C', 'F', -0.04f, 5.2f},
    {'A', 'H', 0.17f, 5.2f},
    {'T', 'A', -0.41f, 5.2f},
    {'D', 'F', 0.22f, 5.2f},
};
static constexpr size_t NUM_FORBIDDEN_W_PATTERNS = 100;

// O(1) lookup table for forbidden W patterns indexed by (aa_before, aa_after)
// Returns r_ratio (0.0f if not forbidden)
struct ForbiddenWLookup {
    // Map AA chars to compact indices (0-25 for A-Z, 26 for invalid)
    static constexpr int aa_index(char c) {
        return (c >= 'A' && c <= 'Z') ? (c - 'A') : 26;
    }
    float table[27][27];

    constexpr ForbiddenWLookup() : table{} {
        for (size_t i = 0; i < NUM_FORBIDDEN_W_PATTERNS; ++i) {
            int bi = aa_index(FORBIDDEN_W_PATTERNS[i].aa_before);
            int ai = aa_index(FORBIDDEN_W_PATTERNS[i].aa_after);
            if (bi < 27 && ai < 27) {
                table[bi][ai] = FORBIDDEN_W_PATTERNS[i].r_ratio;
            }
        }
    }

    float lookup(char aa_before, char aa_after) const {
        int bi = aa_index(aa_before);
        int ai = aa_index(aa_after);
        if (bi >= 27 || ai >= 27) return 0.0f;
        return table[bi][ai];
    }
};

static constexpr ForbiddenWLookup FORBIDDEN_W_LOOKUP{};

// ============================================================================
// AA-impact codon substitution table
// For each codon x position x damage type, does the damage change the AA?
// Uses TCAG encoding (T=0, C=1, A=2, G=3) matching codon_to_idx() convention.
// ============================================================================

// Map nucleotide char to TCAG index (constexpr-safe)
static constexpr int nuc_index(char c) {
    return (c == 'T' || c == 't') ? 0 :
           (c == 'C' || c == 'c') ? 1 :
           (c == 'A' || c == 'a') ? 2 :
           (c == 'G' || c == 'g') ? 3 : -1;
}

// Compute codon index from three nucleotide TCAG indices
static constexpr int codon_index(int c0, int c1, int c2) {
    return (c0 << 4) | (c1 << 2) | c2;
}

// Compute codon index from three nucleotide characters
static constexpr int codon_index_from_chars(char c0, char c1, char c2) {
    return codon_index(nuc_index(c0), nuc_index(c1), nuc_index(c2));
}

struct AAImpactLookup {
    // Standard genetic code in TCAG order
    static constexpr char GENETIC_CODE[64] = {
        'F','F','L','L', 'S','S','S','S', 'Y','Y','*','*', 'C','C','*','W',  // T__
        'L','L','L','L', 'P','P','P','P', 'H','H','Q','Q', 'R','R','R','R',  // C__
        'I','I','I','M', 'T','T','T','T', 'N','N','K','K', 'S','S','R','R',  // A__
        'V','V','V','V', 'A','A','A','A', 'D','D','E','E', 'G','G','G','G',  // G__
    };

    // table[codon_idx][position][damage_type]
    // damage_type: 0 = C->T (deamination at 5'), 1 = G->A (complementary at 3')
    // value: 1 if AA changes, 0 if synonymous or base not susceptible
    uint8_t table[64][3][2];

    constexpr AAImpactLookup() : table{} {
        for (int c0 = 0; c0 < 4; ++c0) {
            for (int c1 = 0; c1 < 4; ++c1) {
                for (int c2 = 0; c2 < 4; ++c2) {
                    int idx = (c0 << 4) | (c1 << 2) | c2;
                    char orig_aa = GENETIC_CODE[idx];
                    int bases[3] = {c0, c1, c2};

                    for (int pos = 0; pos < 3; ++pos) {
                        // C->T (type 0): only if base is C (TCAG index 1)
                        if (bases[pos] == 1) {
                            int mut[3] = {bases[0], bases[1], bases[2]};
                            mut[pos] = 0; // C(1) -> T(0)
                            int mut_idx = (mut[0] << 4) | (mut[1] << 2) | mut[2];
                            table[idx][pos][0] = (GENETIC_CODE[mut_idx] != orig_aa) ? 1 : 0;
                        }
                        // G->A (type 1): only if base is G (TCAG index 3)
                        if (bases[pos] == 3) {
                            int mut[3] = {bases[0], bases[1], bases[2]};
                            mut[pos] = 2; // G(3) -> A(2)
                            int mut_idx = (mut[0] << 4) | (mut[1] << 2) | mut[2];
                            table[idx][pos][1] = (GENETIC_CODE[mut_idx] != orig_aa) ? 1 : 0;
                        }
                    }
                }
            }
        }
    }

    constexpr uint8_t aa_impact(int codon_idx, int pos, int damage_type) const {
        return table[codon_idx][pos][damage_type];
    }
};

static constexpr AAImpactLookup AA_IMPACT_LOOKUP{};

} // namespace dart
