{% set version = "1.0.0" %}

package:
  name: dart-adna
  version: {{ version }}

source:
  url: https://github.com/genomewalker/dart/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a793d7ada138f344fafd5ab9a32fab9c3f25e8b5f857e098efb2b71365e9e928

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make
    - pkg-config
  host:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]
  run:
    - zlib
    - zstd
    - libgomp        # [linux]
    - llvm-openmp    # [osx]

test:
  commands:
    - dart --version
    - dart --help
    - dart predict --help
    - dart hits2emi --help
    - dart damage-annotate --help

about:
  home: https://github.com/genomewalker/dart
  license: MIT
  license_file: LICENSE
  summary: DART — Damage-Aware Read Translation for ancient DNA metagenomics
  doc_url: https://github.com/genomewalker/dart/wiki
  dev_url: https://github.com/genomewalker/dart

extra:
  recipe-maintainers:
    - genomewalker
